name: check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install bats, shellcheck, tmux, jq
        run: sudo apt-get update -q && sudo apt-get install -y -q bats shellcheck tmux jq
      - name: Versions
        run: bats --version && shellcheck --version && tmux -V
      - run: make check
